"""revision11

Revision ID: 1045c92beede
Revises: 3b8be48286e9
Create Date: 2023-06-06 23:00:11.846966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1045c92beede'
down_revision = '3b8be48286e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salarydata', 'user_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('salarydata', 'user_middle_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('salarydata', 'user_last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'user_middle_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'user_last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'user_middle_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('salarydata', 'user_last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('salarydata', 'user_middle_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('salarydata', 'user_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
