"""revision4

Revision ID: 1d72827dd91b
Revises: 2b4054b6fea1
Create Date: 2023-05-31 22:53:37.656740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d72827dd91b'
down_revision = '2b4054b6fea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
