"""revision17

Revision ID: 2aa1c85434b4
Revises: 599291575e1c
Create Date: 2023-06-08 23:38:53.344463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa1c85434b4'
down_revision = '599291575e1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salarydata', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'salarydata', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salarydata', type_='foreignkey')
    op.drop_column('salarydata', 'user_id')
    # ### end Alembic commands ###
