"""revision3

Revision ID: 2b4054b6fea1
Revises: 27c2c8310911
Create Date: 2023-05-31 22:50:43.739377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4054b6fea1'
down_revision = '27c2c8310911'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
