"""revision10

Revision ID: 3b8be48286e9
Revises: 6c85f155e308
Create Date: 2023-06-06 21:53:40.662610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8be48286e9'
down_revision = '6c85f155e308'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salarydata', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'salarydata', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('salary_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'salarydata', ['salary_id'], ['id'])
    op.drop_column('user', 'live_time_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('live_time_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'salary_id')
    op.drop_constraint(None, 'salarydata', type_='foreignkey')
    op.drop_column('salarydata', 'user_id')
    # ### end Alembic commands ###
