"""revision20

Revision ID: 40c8bc480ea9
Revises: cd99ec5eb81c
Create Date: 2023-06-09 00:09:58.727341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c8bc480ea9'
down_revision = 'cd99ec5eb81c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
