"""revision26

Revision ID: 47e951d42f9e
Revises: 9bc18106c9ca
Create Date: 2023-06-10 03:32:07.575433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e951d42f9e'
down_revision = '9bc18106c9ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
