"""revision16

Revision ID: 599291575e1c
Revises: a20c95c0b089
Create Date: 2023-06-06 23:45:24.371698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599291575e1c'
down_revision = 'a20c95c0b089'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('salarydata_user_id_fkey', 'salarydata', type_='foreignkey')
    op.drop_column('salarydata', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salarydata', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('salarydata_user_id_fkey', 'salarydata', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
