"""revision9

Revision ID: 6c85f155e308
Revises: 63c429b078b0
Create Date: 2023-06-06 21:07:48.258120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c85f155e308'
down_revision = '63c429b078b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salarydata', 'time_get_data')
    op.add_column('user', sa.Column('time_create_token', sa.DateTime(), nullable=False))
    op.alter_column('user', 'hashed_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('user', 'live_time_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.drop_column('user', 'time_get_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_get_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('user', 'live_time_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('user', 'hashed_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('user', 'time_create_token')
    op.add_column('salarydata', sa.Column('time_get_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
