"""revision22

Revision ID: 85ee76fc18e0
Revises: c71dbfab2697
Create Date: 2023-06-09 00:21:30.170637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ee76fc18e0'
down_revision = 'c71dbfab2697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salarydata', 'user_last_name')
    op.drop_column('salarydata', 'user_name')
    op.drop_column('salarydata', 'user_middle_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salarydata', sa.Column('user_middle_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('salarydata', sa.Column('user_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('salarydata', sa.Column('user_last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
