"""revision25

Revision ID: 9bc18106c9ca
Revises: d8ad1d0c73e9
Create Date: 2023-06-10 03:26:25.427635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc18106c9ca'
down_revision = 'd8ad1d0c73e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salarydata', sa.Column('time_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salarydata', 'time_update')
    # ### end Alembic commands ###
