"""revision15

Revision ID: a20c95c0b089
Revises: e6f5febea452
Create Date: 2023-06-06 23:37:04.801408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20c95c0b089'
down_revision = 'e6f5febea452'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
