"""revision1

Revision ID: b2241da10232
Revises: 8a7e8b5f9e78
Create Date: 2023-05-31 22:33:59.369834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2241da10232'
down_revision = '8a7e8b5f9e78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
