"""revision13

Revision ID: b5e9055b6621
Revises: b421060d7e2b
Create Date: 2023-06-06 23:09:45.041859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e9055b6621'
down_revision = 'b421060d7e2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salary_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'salarydata', ['salary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'salary_id')
    # ### end Alembic commands ###
