"""revision18

Revision ID: b7301909107c
Revises: 2aa1c85434b4
Create Date: 2023-06-08 23:47:15.313595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7301909107c'
down_revision = '2aa1c85434b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
