"""revision21

Revision ID: c71dbfab2697
Revises: 40c8bc480ea9
Create Date: 2023-06-09 00:14:32.530163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71dbfab2697'
down_revision = '40c8bc480ea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
