"""revision19

Revision ID: cd99ec5eb81c
Revises: b7301909107c
Create Date: 2023-06-08 23:48:35.867216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd99ec5eb81c'
down_revision = 'b7301909107c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_salary_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'salary_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salary_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_salary_id_fkey', 'user', 'salarydata', ['salary_id'], ['id'])
    # ### end Alembic commands ###
