"""revision5

Revision ID: d85cdbe45fd3
Revises: 1d72827dd91b
Create Date: 2023-05-31 22:56:03.962452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85cdbe45fd3'
down_revision = '1d72827dd91b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
