"""revision14

Revision ID: e6f5febea452
Revises: b5e9055b6621
Create Date: 2023-06-06 23:32:00.546730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f5febea452'
down_revision = 'b5e9055b6621'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
